### ISSUE TITLE
Hola estoy probando tu script y me da este problema

### ISSUE THREAD

**Issue by felisucoibi** [fabrebatalla18/apuntmedia-downloader#1]
Hola estoy probando tu script y me da este problema, me ha pasado tu enlace un compañero de retroshare. El comando que pongo:
python "./apuntmedia36.py" --carpeta "./Descargas" --no-descargar --pagina-inicial 0 --pagina-final 10 --url "https://www.apuntmedia.es/va/la-colla/infantil/detectiu-conan"

`Buscando IDs en la página web...
Traceback (most recent call last):
  File "./apuntmedia36.py", line 215, in <module>
    A=find_str(str(x), '<h2 class="title"><span class="programas"></span>')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 212: ordinal not in range(128)
`

**Comment by fabrebatalla18** [comment]
Que python usas? A mi me ha funcionado bien en 3.4 y 3.6.

**Comment by felisucoibi** [comment]
Python 2.7.15rc1 con linux

**Comment by fabrebatalla18** [comment]
Ahí esta tu problema, usa Python 3, recomiendo 3.6 que es donde lo he creado y probado.

**Comment by felisucoibi** [comment]
funciona, no nos ha bajado nada, pero el .txt lo ha creado genial.

**Comment by fabrebatalla18** [comment]
Claro, porque para que lo descargue tienes que quitar el comando "--no-descargar". 
Como veo que os funciona cierro el issue.
