### ISSUE TITLE
el nuevo sistema de bajar por carpetas tiene un bug

### ISSUE THREAD

**Issue by felisucoibi** [fabrebatalla18/apuntmedia-downloader#4]
el nuevo sistema de bajar por carpetas tiene un bug que hace que cada archivo lo baje anidado en una nueva carpeta con el mismo nombre dentro de la carpeta anterior... con lo que se crea un arbol del tipo

./conan/conan/connan/ etc...

**Comment by fabrebatalla18** [comment]
Solucionado.
